---
title: "<span class='ex-title'>Spatial Data Analysis with R:</span><br/><span class='ex-subtitle'>Outline</span>"
author: "`r load('common/course_info.RData'); lstCI$course`"
output: 
  html_document: 
    css: common/slidy_styles.css
    self_contained: no
    lib_dir: exercises/lib
    smart: no
    includes:
      in_header: common/header.html
---
<style>
li {
  margin-top:1em;
}
h1 {
  font-size: 130%;
}
</style>

```{r include=FALSE}
load('common/course_info.RData')
```

# `r lstCI$class01short`. Introduction to R  

<li class="slide"><a target="_blank" class="slide" href="slides/part01a_intro.html">Intro</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part01b_rsyntax.html">R Syntax</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex01_basicr.html">Exercise 1: Basic Operations</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part01c_packages.html">Working with Packages</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex02_packages.html">Exercise 2: Packages</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part01d_import_plot.html">Importing and Plotting Spatial Data</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex03_import_plot.html">Exercise 3: Import and Plot Data</a></li>

# `r lstCI$class02short`. Two Dimensional Data Structures, R Markdown, Spatial Data Classes, Projections, Queries, Geoprocessing

<li class="slide"><a target="_blank" class="slide" 
href="slides/part02a_review.html">Review from Last Time</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part02b_sort-save-misc.html">More R Fundamentals</a></li>

<li class="exercise"><a target="_blank" class="exercise" href="exercises/ex04_sort-save-misc.html">Exercise 4: Lists, Sorting and Saving Data</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part02c_2d-data.html">Matrices and data frames</a></li>
  
<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex05_dataframes.html">Exercise 5: Working with Data Frames</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part02d_rmarkdown.html">R Markdown</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part02e_spatial-data.html">Spatial Data Basic Operations</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex06_spatial-data-ops.html">Exercise 6: Spatial Data Operations</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part02f_geoprocessing.html">Geoprocessing</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex07_geoprocessing.html">Exercise 7: Geoprocessing</a></li>

# `r lstCI$class03short`. Loops and branches, spatial queries, raster data, APIs, geocoding

<li class="slide"><a target="_blank" class="slide" 
href="slides/part03a_control-structures.html">Control Structures</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex08_loops-branches.html">Exercise 8: Loops and Branches</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part03b_spatial-queries.html">Spatial Queries</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex09_spatial-queries.html">Exercise 9: Spatial Queries</a></li>

<!--
Compute the density of canabis dispensaries per NB.
Create a random set of points in a county (sampling points)
-->

<li class="slide"><a target="_blank" class="slide" 
href="slides/part03c_raster-pt1.html">Raster Data Pt 1</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex10_raster01.html">Exercise 10: Importing Raster Data</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part03d_raster-pt2.html">Raster Data Pt 2</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex11_raster02.html">Exercise 11: Derived Data</a></li>

<li class="slide"><a target="_blank" class="slide" 
href="slides/part03e_geocoding.html">Geocoding</a></li>

<li class="exercise"><a target="_blank" class="exercise"
href="exercises/ex12_geocoding.html">Exercise 12: Geocoding</a></li>

# `r lstCI$class04short`. Custom functions, working with models, ggmap & leaflet, projects, R-ArcGIS integration


# Resources

* [Where to Turn Next](slides/where_to_turn_next.html){target="_blank"}

* Cheatsheets

    + [General R](extras/general-r_cheatsheet_animove.pdf)
    + [Data Management](extras/data-management_cheatsheet.pdf)
    + [R Color palettes](extras/color-palette_cheatsheet.pdf)
    + [spatial operations](extras/spatial-commands_cheatsheet_animove_2014-05-11.pdf)
    + [coordinate reference systems](extras/coordinate-ref-systems_overview.pdf)
    + [remote sensing & GIS functions](extras/RS_ecology_refcard.pdf)
    + [ArcGIS equivalents in R](extras/arcgis_to_r_spatial_cheatsheet.pdf)
    + [ggmap quickstart](extras/ggmap_cheatsheet.pdf)

* [Workshop Etherpad](https://public.etherpad-mozilla.org/p/rspatial-baygeo-s18){target="_blank"}
